"""add assignee to tickets

Revision ID: 11aedbd6f2fe
Revises: 97ca184d6ddd
Create Date: 2026-07-22 16:55:53.899341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11aedbd6f2fe'
down_revision: Union[str, Sequence[str], None] = '97ca184d6ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assignee', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assignee')
    # ### end Alembic commands ###
